#!/bin/bash
rm *.aux
pdflatex -interaction=batchmode -draftmode 0_researchnotes.tex
makeindex 0_researchnotes
for auxfile in ch_*.aux; do
    bibtex `basename $auxfile .aux`
done
for auxfile in ap_*.aux; do
    bibtex `basename $auxfile .aux`
done
pdflatex -interaction=batchmode -draftmode 0_researchnotes.tex
pdflatex -interaction=batchmode 0_researchnotes.tex
./distclean
