#!/bin/bash

#
# bibtex stuff
#
pdflatex -shell-escape -draftmode -halt-on-error 0_researchnotes.tex
if [ $? -ne 0 ]; then
    echo "Compilation failed! Rerun with makelatex to learn more."
    exit
fi
for auxfile in ch_*.aux; do
    bibtex `basename $auxfile .aux`
done
for auxfile in ap_*.aux; do
    bibtex `basename $auxfile .aux`
done

#
# feynman diagrams
#
diagrams=(fr123 fr4to17 fr18to21 fr22to25 fr26 prob1 prob2)
for diagram in "${diagrams[@]}"; do
  if [ ! -f ${diagram}.mf ]; then mf ${diagram}; fi
done

#
# index
#
pdflatex -interaction=batchmode -shell-escape -draftmode 0_researchnotes.tex > /dev/null 2>&1
makeindex -s indexHeader.ist 0_researchnotes
python scripts/fixIndex.py
mv temp.idx 0_researchnotes.idx
mv temp.ind 0_researchnotes.ind
pdflatex -interaction=batchmode -shell-escape -draftmode 0_researchnotes.tex > /dev/null 2>&1


pdflatex -interaction=batchmode -shell-escape 0_researchnotes.tex
./distclean
