#!/bin/bash
rm *.aux
pdflatex 0_researchnotes.tex
for auxfile in ch_*.aux; do
    bibtex `basename $auxfile .aux`
done
for auxfile in ap_*.aux; do
    bibtex `basename $auxfile .aux`
done

#
# feynman diagrams
#
diagrams=(fr123 fr4to17 fr18to21 fr22to25 fr26 prob1 prob2)
for diagram in "${diagrams[@]}"; do
  rm ${diagram}*
  mf ${diagram}
done

pdflatex 0_researchnotes.tex
makeindex 0_researchnotes
python scripts/fixIndex.py
mv temp.idx 0_researchnotes.idx
mv temp.ind 0_researchnotes.ind
pdflatex 0_researchnotes.tex
pdflatex 0_researchnotes.tex
./distclean
