#!/bin/bash
rm *.aux
pdflatex probabilitynotes.tex
for auxfile in ch_*.aux; do
    bibtex `basename $auxfile .aux`
done
for auxfile in ap_*.aux; do
    bibtex `basename $auxfile .aux`
done
pdflatex probabilitynotes.tex
pdflatex probabilitynotes.tex
./distclean
